# Generated by Django 3.2.10 on 2021-12-22 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gamepage_genresorderable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamepage',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
